org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.20.1
forge_version=47.4.0
dynamic_trees_version=1.4.11
dynamic_trees_file_id=8227003
dynamic_trees_plus_version=1.20.1-1.2.2
dynamic_trees_plus_file_id=7502535
betternether_version=20.0.10
betternether_file_id=7713601
bclib_forge_file_id=7780396
wunderlib_forge_file_id=7486522

mod_id=dtbetternether
mod_name=Dynamic Trees for Better Nether
mod_version=1.6.0
mod_group_id=com.dannykim.dtbetternether
mod_authors=dannykim
mod_license=MIT
mod_description=Compatibility between Dynamic Trees and BetterNether

